### ISSUE TITLE
Sync with delete option

### ISSUE THREAD

**Issue by alexandrovas** [huaweicloud/huaweicloud-obs-obsutil#3]
Hello!
I found out that this utility cannot delete files in the destination directory during synchronization.

Will this feature be implemented?

I work in a large project, which is a client of [Sbercloud](https://sbercloud.ru/en/advanced), which is built on the basis of Huaweicloud.

We want to use this utility to periodically synchronize our buckets.

**Comment by x00403408** [comment]
I am not quite sure about your purpose; 
If you want to delete the uploaded files, you can use the "arcDir" parameter to archive  the synchronously uploaded files  to the specified path, and then you can delete the archive path by yourself;
If you mean that you want to delete the objects in the bucket which has been downloaded, I'm afraid we do not support this operation now; Because deleting user objects in the bucket is a high-risk operation, we will be cautious about feature that need to delete user objects ;

**Comment by alexandrovas** [comment]
@x00403408 
Hello!
What I mean is creating a complete mirror of one bucket to another with the deletion of unnecessary files in the destination bucket.
For example, the s3сmd utility is able to do this: https://s3tools.org/s3cmd-sync (see —delete-removed option).

**Comment by x00403408** [comment]
I got it；Considering the risks associated with deleting object, I am afraid we may not provice similar method in a short time; sorry for that

**Comment by x00403408** [comment]
Since no new reply has been received within one month, the issue will be closed；
